In [1]:
import numpy as np
import pandas as pd

In [328]:
mdp = 'data/mdp/episodic-mdp-10-5.txt'

In [329]:
df = pd.read_csv(mdp,)
df

numStates 10
0                                         numActions 5
1                                              start 6
2                                              end 0 5
3    transition 1 0 6 -0.37970486136133474 0.049335...
4    transition 1 0 5 0.4596634965202573 0.17220113...
..                                                 ...
118  transition 9 3 7 -0.7086191560928488 0.5180722...
119  transition 9 3 6 0.7836842174233938 0.24479737...
120            transition 9 4 6 0.3728362085971162 1.0
121                                   mdptype episodic
122                                      discount  1.0

[123 rows x 1 columns]

In [332]:
dict_mdp = {}
a=[]
with open(mdp) as fp:
    lines = fp.readlines()
    for line in lines:
        a.append(line.split())

In [241]:
Reward[0][0][:]

array([-0.91903124,  0.93092977])

In [105]:
d = {}
n=len(a)
for i,j in enumerate(a[4:n-3]):
    
    d[j[1]]={}
    d[j[1]][j[2]]={}
    d[j[1]][j[2]][j[3]]={}
    



# dict_trans['trans'] = {}
# #dict_reward = {}
# for i in range(4,len(a)-2):
#     dict_trans[a[i][1]] = {}
#     dict_trans[a[i][1]][a[i][2]] = {}
#     dict_trans[a[i][1]][a[i][3]] = {} 
#     dict_trans[a[i][1]][a[i][2]][a[i][3]] = a[i][4]
#     #dict(d)
#     #dict_reward[a[i][1]][a[i][2]][a[i][3]] = a[i][5]

In [121]:
a[2][1]

'0'

In [94]:
b=[[2,3],[3,4],4]
for i,j in enumerate(b[0:2]):
    print(i,j[0])

0 2
1 3


In [334]:
a

[['numStates', '10'],
 ['numActions', '5'],
 ['start', '6'],
 ['end', '0', '5'],
 ['transition', '1', '0', '6', '-0.37970486136133474', '0.04933586337760911'],
 ['transition', '1', '0', '5', '0.4596634965202573', '0.1722011385199241'],
 ['transition', '1', '0', '3', '0.797676575935987', '0.21110056925996204'],
 ['transition', '1', '0', '8', '0.36796786383088254', '0.15370018975332067'],
 ['transition', '1', '0', '9', '-0.055714569094573285', '0.41366223908918404'],
 ['transition', '1', '1', '1', '-0.8134562712951798', '0.8329519450800915'],
 ['transition', '1', '1', '9', '0.6801824331108262', '0.16704805491990846'],
 ['transition', '1', '2', '6', '-0.5227681427695596', '0.06252382767823103'],
 ['transition', '1', '2', '4', '0.9350805005802867', '0.170987418985894'],
 ['transition', '1', '2', '3', '0.6063589385597401', '0.09931376286694625'],
 ['transition', '1', '2', '0', '-0.10406085712885926', '0.18223408311094166'],
 ['transition', '1', '2', '9', '-0.8391083628949292', '0.4849409073

In [127]:
len(a[3])

2

In [24]:
from pulp import *

# Try Here

In [336]:
mdp = 'data/mdp/episodic-mdp-10-5.txt'
a = []
with open(mdp) as fp:
    lines = fp.readlines()
    for line in lines:
        a.append(line.split())



In [337]:
nS = int(a[0][1])
nA = int(a[1][1])
dt = {}
end = []
for i in range(1,len(a[3])):
    end.append(a[3][i])
endS = np.array(end.copy())
dt['mdptype'] = a[-2][1]
dt['gamma'] = float(a[-1][1])
dt['start'] = int(a[2][1])
Reward = np.zeros((nS,nA,nS))
tranProb = np.zeros((nS,nA,nS))
m = len(a)
for i in range(4,len(a)-2):
    Reward[int(a[i][1])][int(a[i][2])][int(a[i][3])] = float(a[i][4])
    tranProb[int(a[i][1])][int(a[i][2])][int(a[i][3])] = float(a[i][5])

In [339]:
tranProb

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 0.21110057, 0.        ,
         0.17220114, 0.04933586, 0.        , 0.15370019, 0.41366224],
        [0.        , 0.83295195, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.16704805],
        [0.18223408, 0.  

In [293]:
np.shape(Reward[1,0,:])


(10,)

In [294]:
class MDPs():
    """docstring for MDPs"""
    def __init__(self, nS,nA,Reward,tranProb,gamma,mdptype):

        self.nS = nS
        self.nA = nA
        self.Reward = Reward
        self.tranProb = tranProb
        self.gamma = gamma
        self.mdptype = mdptype
    def VI(self):
        Vi = np.zeros(self.nS)
        Vf = np.zeros(self.nS)

        pi = np.zeros(self.nS)

        count=0
        while True:
            Vf = np.zeros(self.nS)
            pi = np.zeros(self.nS)
            for s in range(self.nS):
                max_tmp = np.sum((self.tranProb[s,0,:])*(self.Reward[s,0,:]+(self.gamma)*Vi))
                for a in range(1,self.nA):
                    tmp = np.sum((self.tranProb[s,a,:])*(self.Reward[s,a,:]+(self.gamma*Vi)))
                    if tmp > max_tmp:
                        pi[s]=a
                        max_tmp = tmp
                Vf[s] = max_tmp
        

            if np.allclose(Vf, Vi, rtol=1e-13, atol=1e-15) or count > 100000 :
                    break
            Vi = Vf.copy()
            count+=1
        #print(count)
        return Vf, pi

        
    def HPI(self):
        #Vprime = np.zeros(self.nS)
        pi = np.zeros(self.nS,int)
        flag = 1
        count=0
        while flag:
            #solve n linear equations
            prob = LpProblem("finding_V")
            Vs = LpVariable.dicts("V",range(self.nS))
            
            for s in range(self.nS):
                if self.mdptype == "episodic" and s == (self.nS-1) :
                    prob += Vs[self.nS-1] == 0
                else:
                    prob += Vs[s] == lpSum([self.tranProb[s][pi[s]][sprime]*(self.Reward[s][pi[s]][sprime] + self.gamma*Vs[sprime]) for sprime in range(self.nS)])
                 
            prob.solve()
            Vsn = np.array([Vs[i].value() for i in range(self.nS)])
            
            #Implementation of policy imporvement
            #if improving action is found we will change the policy
            for s in range(self.nS):
                if self.mdptype == "episodic" and s == (self.nS-1) :
                    continue
                for a in range(self.nA):
                    Q = np.sum((self.tranProb[s][a][:])*(self.Reward[s][a][:] + self.gamma*Vsn[:]))
                        
                    #if Q(s,a) > Vs(s) we will update policy
                    #print(Q - Vs[s].value())
                    if (Q - Vs[s].value() > 1e-6):
                        pi[s] = a
                        flag = 1
                        break
            count+=1
            if count==100:
                break
            #print(count)
        #when above while loop breaks it will give optimal policy
        #now we have to calculate updated Vstart(optimal value function) for updated policy
        prob_new= LpProblem("finding_Vstar")
        Vstar = LpVariable.dicts("V", range(self.nS))
        for s in range(self.nS):
            if self.mdptype == "episodic" and s == (self.nS-1):
                prob_new += Vstar[self.nS-1] == 0.0
            else:
                prob_new += Vstar[s] == lpSum([self.tranProb[s][pi[s]][sprime]*(self.Reward[s][pi[s]][sprime] + self.gamma*Vstar[sprime]) for sprime in range(self.nS)])

        prob_new.solve()
        Vf=np.zeros(self.nS)
        for s in range(self.nS):
            Vf[s] = Vstar[s].value()
        return Vf, pi
    
    
    def LP(self):
        Vstar = []
        piStar = []
        prob = LpProblem("MDP_using_lp", LpMinimize)
        Vs = LpVariable.dicts("Value_of_state",range(self.nS))
        prob += lpSum([Vs[i] for i in range(self.nS)])
        for s in range(self.nS):
            if self.mdptype == 'episodic':
                if s == self.nS -1:
                    prob += Vs[s] == 0.0
            for a in range(self.nA):
                prob += Vs[s] >= lpSum([self.tranProb[s][a][s1]*(self.Reward[s][a][s1] + self.gamma*Vs[s1] ) for s1 in range(self.nS)])

        prob.solve()

        #Finding actions for the value function
        actions = []
        for s in range(self.nS):
            for a in range(self.nA):
                v = 0
                for s1 in range(self.nS):
                    v += self.tranProb[s][a][s1]*(self.Reward[s][a][s1] + self.gamma*Vs[s1].value())
                if(abs(v - Vs[s].value()) < 1e-7):
                    Vstar.append(Vs[s].value())
                    piStar.append(a)
                    break
                
        return Vstar, piStar        

In [295]:
sol = MDPs(nS, nA, Reward, tranProb, dt['gamma'], dt['mdptype'])

In [296]:
Vstar, piStar = sol.LP()
for i in range(nS):
    print(Vstar[i]," ",piStar[i])

0.0   0
19.193935   1
0.0   0
20.881683   2


IndexError: list index out of range

In [203]:
ans = pd.read_csv("data/mdp/sol-continuing-mdp-50-20.txt", header = None,delimiter='')

In [277]:
ans.columns=['ans1', 'ans2']

print(str(format(ans['ans1'][0],'0.6f')),(format(Vstar[0],'0.6f')))

1.065079 1.065079


In [281]:
for i in range(50):
    if (str(format(ans['ans1'][i],'0.6f'))!=(format(Vstar[i],'0.6f'))):
        print(i)

1
38


In [9]:
def Bellman(T, R, V, gamma):
    numStates = np.size(T)
    T = np.reshape(T, (numStates, 1))
    R = np.reshape(R, (numStates, 1))
    R = R + gamma * V
    result = np.matmul(np.transpose(T), R)
    return result

In [10]:
Bellman(tranProb, Reward, np.zeros(nS),dt['gamma'])

array([[1.48655402, 1.48655402, 1.48655402, 1.48655402, 1.48655402,
        1.48655402, 1.48655402, 1.48655402, 1.48655402, 1.48655402]])

In [11]:
np.size(tranProb)

500

In [344]:
from operator import mul, add

class MDPs():
    """docstring for MDPs"""
    def __init__(self, nS,nA,Reward,tranProb,gamma,mdptype):

        self.nS = nS
        self.nA = nA
        self.Reward = Reward
        self.tranProb = tranProb
        self.gamma = gamma
        self.mdptype = mdptype
    def VI(self):
        Vi = np.zeros(self.nS)
        Vf = np.zeros(self.nS)

        pi = np.zeros(self.nS)

        count=0
        while True:
            Vf = np.zeros(self.nS)
            pi = np.zeros(self.nS)
            for s in range(self.nS):
                max_tmp = np.sum((self.tranProb[s,0,:])*(self.Reward[s,0,:]+(self.gamma)*Vi))
                for a in range(1,self.nA):
                    tmp = np.sum((self.tranProb[s,a,:])*(self.Reward[s,a,:]+(self.gamma*Vi)))
                    if tmp > max_tmp:
                        pi[s]=a
                        max_tmp = tmp
                Vf[s] = max_tmp
        

            if np.allclose(Vf, Vi, rtol=1e-13, atol=1e-15) or count > 100000 :
                    break
            Vi = Vf.copy()
            count+=1
        print(count)
        return Vf, pi
    def Value_function(self, s, pi):
        V = np.zeros(self.nS)
        eps = 1e-7
        V1 = np.ones(self.nS)
        while (np.linalg.norm(V1-V, ord=np.inf))>eps:
            V = V1
            V = V.reshape(1,1,self.nS)
            V1 = np.sum(self.tranProb[s, pi,:]*(self.Reward[s, pi,:] + self.gamma*V), axis=-1)
            V = V.reshape(-1)
        return V
        
            
    def hpi(self):

        pi = np.zeros(self.nS, dtype=int)
        s = np.array([i for i in range(self.nS)])
        Vs = self.Value_function(s, pi)
        Qs = np.sum(self.tranProb*(self.Reward+self.gamma*V), axis=-1)
        Vs = Vs.reshape(self.nS, 1)
        x = Qs-Vs
        tmp_max = np.argmax(x, -1)
        while(not np.all(pi==tmp_max)):
            pi = tmp_max
            Vs = self.Value_function(s, pi)
            Qs = np.sum(self.tranProb*(self.Reward+self.gamma*V), axis=-1)
            Vs = Vs.reshape(self.nS, 1)
            x = Qs-Vs
            if x.any()>0:
                tmp_max = np.argmax(x, -1)
        Vs = self.Value_function(s, pi)
        Vs = Vs.reshape(self.nS)
        return Vs,pi
#         for i in range(self.nS):
#             print('%10.6f'%V[i],'\t',pi[i])
            
#     def lp(self):
#         n = self.nS
#         k = self.num_actions
#         mdp = LpProblem("MDP", LpMaximize)
#         Var = LpVariable.dict("Value_Function", range(n))
#         mdp += lpSum([-Var[i] for i in range(n)])
#         V = np.zeros((n, 1, 1), dtype = LpVariable)
#         for i in range(n):
#             V[i][0] = Var[i]
        
#         for i in range(n):
#             for j in range(k):
#                 val = self.val_fn(i, j, V)
#                 mdp += Var[i]>=val
            
        
#         mdp.solve(pulp.PULP_CBC_CMD(msg=0))
#         V = np.zeros((self.num_states, 1))
#         for i in range(self.num_states):
#             V[i, 0] = Var[i].varValue

#         V = V.reshape((1,1,self.num_states))
#         pi = np.argmax(np.sum(self.T*(self.R + self.gamma*V), axis=-1), axis=-1)
#         V = V.reshape(self.num_states)
        
#         for i in range(self.num_states):
#             print('%10.6f'%V[i],'\t',pi[i]) 
      
    def val_fn(self, s, a, V):
        T = self.tranProb[s, a, :]
        R = self.Reward[s, a, :]
        T = T.reshape((self.nS, 1))
        V = V.reshape((self.nS, 1))
        R = R.reshape((self.nS, 1))
        R = R + self.gamma*V
        x = np.transpose(T).dot(R)
        return x[0][0]
         
        
            
        
        
        
        
            
    
        
    
       

In [345]:
sol = MDPs(nS, nA, Reward, tranProb, dt['gamma'], dt['mdptype'])
Vstar, piStar = sol.hpi()
for i in range(nS):
    print(Vstar[i]," ",piStar[i])

ValueError: operands could not be broadcast together with shapes (10,5,10) (50,1) 

In [387]:
file_name = "data/maze/grid20.txt"
f = open(file_name)
lines = [[i for i in line.split()] for line in f.read().split('\n')]
f.close()
lines.pop()

[]

In [395]:
for i in range(len(lines)):
    #for j in range(len(lines)):
    
    print(lines[i][:])

1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1

1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1 0 1 0 1

1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 3 1

1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1

1 0 1 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0 1 0 1

1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1

1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1

1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 1

1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 1

1 0 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1

1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1

1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 1 1

1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1

1 1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 1 1

1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1

1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1

1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1

1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1

1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1

1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1



In [393]:
a = []
with open(file_name) as fp:
    lines = fp.readlines()
    for line in lines:
        a.append(line.split())


In [400]:
import numpy as np
import sys, argparse

parser = argparse.ArgumentParser()

def main():

parser.add_argument("--grid",help='path to grid file')
args = parser.parse_args()

mdpfile = args.grid
file = open(filepath)

a = [[i for i in line.split()] for line in f.read().split("\n")]
file.close()
a.pop()
n = len(a)
nS = 0
states = {}

for i in range(1,n-1):
for j in range(1,n-1):
    if a[i][j] == "1":
        continue
    else:
        states[(i-1)*(n-1)+(j-1)] = nS
        nS+=1

        if a[i][j]=="2":
            start_state = states[(i-1)*(n-1)+(j-1)]
        elif a[i][j]== '3':
            end_states = states[(i-1)*(n-1)+(j-1)]
#start printing as MDP formulation
print("num_states",nS)
print("numActions",4)
print("start".start_state)
print("end", end_states)
for i in range(1, n-1):
for j in range(1, n-1):
    if (i-1)*(n-1)+(j-1) in s and states[(i-1)*(n-1)+(j-1)]!=end:
        if a[i-1][j]=='0':
            print("transition", states[(i-1)*(n-1)+(j-1)], 0, states[(i-2)*(n-1)+(j-1)], -1, 1)
        elif a[i-1][j]=='3':
            print("transition", states[(i-1)*(n-1)+(j-1)], 0, states[(i-2)*(n-1)+(j-1)], nS*2, 1)

        if a[i+1][j]=='0':
            print("transition", states[(i-1)*(n-1)+(j-1)], 3, states[i*(n-1)+(j-1)], -1, 1)
        elif a[i+1][j]=='3':
            print("transition", states[(i-1)*(n-1)+(j-1)], 3, states[i*(n-1)+(j-1)], nS*2, 1)

        if a[i][j-1-1]=='0':
            print("transition", states[(i-1)*(n-1)+(j-1)], 2, states[(i-1)*(n-1)+(j-2)], -1, 1)
        elif a[i][j-1]=='3':
            print("transition", states[(i-1)*(n-1)+(j-1)], 2, states[(i-1)*(n-1)+(j-2)], nS*2, 1)

        if a[i][j+1]=='0':
            print("transition", states[(i-1)*(n-1)+(j-1)], 1, states[(i-1)*(n-1)+j], -1, 1)
        elif a[i][j+1]=='3':
            print("transition", states[(i-1)*(n-1)+(j-1)], 1, s[(i-1)*(n-1)+j], nS*2, 1)

print("mdptype episodic")
print("discount ", 0.95)

if __name__ == "__main__":
main()

IndentationError: expected an indented block (<ipython-input-400-ea42ef99f297>, line 8)

In [300]:
Bellman(tranProb, Reward, np.zeros(nS), 0.9)

array([[5.0295264, 5.0295264, 5.0295264, 5.0295264, 5.0295264, 5.0295264,
        5.0295264, 5.0295264, 5.0295264, 5.0295264]])